# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: cryptopals
version: '0.0.0'
github: "githubuser/cryptopals"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: cryptopals is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - bytestring
  - base64-bytestring
  - base16-bytestring
  source-dirs: library

executables:
  cryptopals:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - cryptopals
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  cryptopals-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - cryptopals
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  cryptopals-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - cryptopals
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
